[package]
name = "tonic-disable-doctest"
version = "0.1.0"
authors = ["Sukhmel Vladislav <sukhmel.v@gmail.com>"]
edition = "2021"

[dependencies]
convert_case = "0.6"
itertools = "0.10"
tonic-build = "0.9"
